### Post - Criação do Recurso Instituto, passando como body nome e acronimo
POST http://localhost:8080/institute/ HTTP/1.1
content-type: application/json

{
    "nome": "Ciência e Tecnologia",
    "acronimo": "CITEC"
}

### Post - Criação do Recurso Instituto, passando como body nome e acronimo
POST http://localhost:8080/institute/ HTTP/1.1
content-type: application/json

{
    "nome": "Anatomia e Fisiologia",
    "acronimo": "ANAFI"
}

### Post - Criação do Recurso Instituto, passando como body nome e acronimo
POST http://localhost:8080/institute/ HTTP/1.1
content-type: application/json

{
    "nome": "Bioquímica",
    "acronimo": "BIOQ"
}

### Post - Criação do Recurso Instituto, passando como body nome e acronimo - ../institute/
POST http://localhost:8080/institute/ HTTP/1.1
content-type: application/json

{
    "nome": "Línguas e Letras",
    "acronimo": "LINLE"
}

### Get - Obtenção da lista completa de institutos - ../institute/list
GET  http://localhost:8080/institute/list HTTP/1.1

### DELETE - Delete de um instituto específico - ../institute/{id}
DELETE   http://localhost:8080/institute/2 HTTP/1.1

### Get - Obtenção de um acronimo que contem a palavra específica - ../institute/acronym/{acronimo}
GET  http://localhost:8080/institute/acronym/ANAFI HTTP/1.1

### Get - Obtenção de um nome que contem a palavra específica - ../institute/name/{nome}
GET  http://localhost:8080/institute/name/Anatomia HTTP/1.1

### Get - Obtenção de um nome e ou acronimo que contem a palavra específica - ../institute/lista/{busca}
GET  http://localhost:8080/institute/name-acronym/ana HTTP/1.1

### Put - Atualização do nome e acrônimo de um instituto.
PUT http://localhost:8080/institute/update/1 HTTP/1.1
content-type: application/json

{
    "nome": "Línguas e Letras",
    "acronimo": "LINLE"
}